name: build_pkg

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build package
      run:
        bash makepkg_deb.sh
    - name: Archive code coverage results
          uses: actions/upload-artifact@v4
          with:
            name: Deb package
            path: oink_*.deb